C0FHIRNOTE ;VAMC/JS-FHIR TIU NOTE EXTRACTOR ; 19-JAN-2026
 ;;1.0;C0FHIR PROJECT;;Jan 19, 2026;Build 1
 Q
GETNOTES(RESULT,DFN,ENCPTR) ;RPC: C0FHIR GET NOTES
 ; File #8925: TIU DOCUMENT -> .01:DOCUMENT TYPE; .05:STATUS
 N TIUIEN,CNT,BNDL,STAT,ERR
 S CNT=0 K RESULT
 S TIUIEN=0 F  S TIUIEN=$O(^TIU(8925,"V",ENCPTR,TIUIEN)) Q:'TIUIEN  D
 . S STAT=$$GET1^DIQ(8925,TIUIEN_",",.05,"I","","ERR") Q:STAT<7
 . S CNT=CNT+1
 . S BNDL("entry",CNT,"resource","resourceType")="DocumentReference"
 . S BNDL("entry",CNT,"resource","type","text")=$$GET1^DIQ(8925,TIUIEN_",",.01,"","","ERR")
 . D GENWP(TIUIEN,.BNDL,CNT)
 D ENCODE^XLFJSON("BNDL","RESULT")
 Q
 ;
GENWP(TIUIEN,BNDL,CNT) ;Extract WP Text (File #8925: TIU DOCUMENT -> Field 2: REPORT TEXT)
 N TEXT,FULLTXT,I,ERR
 K TEXT D GET1^DIQ(8925,TIUIEN_",",2,"","TEXT","ERR")
 S FULLTXT="",I=0
 F  S I=$O(TEXT(I)) Q:'I  S FULLTXT=FULLTXT_TEXT(I)_$C(13,10)
 S BNDL("entry",CNT,"resource","content",1,"attachment","data")=$$BASE64^C0FHIRUTL(.FULLTXT)
 Q