C0FHIRGF ;VAMC/JS-FHIR METADATA AGGREGATOR ; 17-FEB-2026
 ;;1.2;C0FHIR PROJECT;;Feb 17, 2026;Build 2
 Q
GENFULL(RESULT,DFN,ENCPTR,SDT,EDT) ;RPC Entry
 N BNDL,CNT,GLB S CNT=0,GLB=$NA(^TMP("C0FHIRGF",$J)) K @GLB,RESULT
 S BNDL("resourceType")="Bundle",BNDL("type")="collection"
 ;
 ; Use the static global crawler
 D CRAWL("C0FHIR PATIENT ID",DFN,.BNDL,.CNT)
 D CRAWL("C0FHIR VITAL MEASUREMENT",DFN,.BNDL,.CNT)
 D CRAWL("C0FHIR LAB RESULT",DFN,.BNDL,.CNT)
 ;
 S BNDL("total")=CNT
 D ENCODE^XLFJSON("BNDL",GLB)
 M RESULT=@GLB K @GLB
 Q
 ;
CRAWL(ENAME,ID,BNDL,CNT) ; Static Crawler
 N IIEN,RES,MAP,NODE,TAG,FILE,FLD,X11,X12,VAL,VALUE
 S RES=$G(^C0FHIR(1.5,ENAME,"RES")) Q:RES=""
 ;
 S IIEN=0 F  S IIEN=$O(^C0FHIR(1.5,ENAME,"ITEMS",IIEN)) Q:'IIEN  D
 . S NODE=^C0FHIR(1.5,ENAME,"ITEMS",IIEN)
 . S TAG=$P(NODE,U),FILE=$P(NODE,U,2),FLD=$P(NODE,U,3)
 . S X11=$G(^C0FHIR(1.5,ENAME,"ITEMS",IIEN,1.1))
 . S X12=$G(^C0FHIR(1.5,ENAME,"ITEMS",IIEN,1.2))
 . ;
 . I X11'="" X X11
 . S VAL="" I FILE,FLD S VAL=$$GET1^DIQ(FILE,ID_",",FLD,"I")
 . I X12'="" S VALUE=VAL X X12 S VAL=VALUE
 . ;
 . I VAL'="" D SETPATH^C0FHIRUTL(.MAP,TAG,VAL)
 ;
 I $D(MAP) S CNT=CNT+1,BNDL("entry",CNT,"resource","resourceType")=RES M BNDL("entry",CNT,"resource")=MAP
 Q